apiVersion: v1
kind: Secret
metadata:
  name: autoscaler
data:
  azure-sp-app-id: ZWQ2Mzk1NjUtODZiYS00YjhjLTgzZWUtYTVkMTZiMjViZjBi
  azure-sp-secret: UjBiMHRodzIwMTc=
  azure-sp-tenant-id: NzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3