apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: c2t5bmV0c3RvcmFnZTI=
  azurestorageaccountkey: V0VZTk5qOFFlNFBiRGN4cEJqZkNxMGZxRllaQ3RRNGZWMm91eWtuSVhTUVZXNEVzT3dTT21KZ2xteG5neUFSWjNoTUFxa2tJWWdtTXg4OXJMWUNNTEE9PQ==